

export const metadata = {
    title: "Shopi Store",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({ children }) {
    return (
      <div className={`antialiased `}>
        {children}
      </div>
    );
  }
  