import Sidebar from "./components/Sidebar";

export const metadata = {
  title: "Shopi Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div
      className={`bg-gradient-to-r from-gray-100 to-gray-200 flex items-end justify-end`}
    >
      <Sidebar />
      {children}
    </div>
  );
}
